import json
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
PRODUCTS_FILE = PROJECT_ROOT / "data" / "products.json"

categories_data = {
    "laptop": [
        ("Lenovo IdeaPad Slim 5", "Lenovo", 18990000, "Laptop mong nhe cho sinh vien, hoc lap trinh va lam viec van phong.", {"cpu": "Intel Core i5-12450H", "ram": "16GB", "storage": "512GB SSD"}, ["student", "programming", "office", "lightweight"]),
        ("Asus TUF Gaming A15", "Asus", 22990000, "Laptop gaming tam trung, phu hop cho game, do hoa co ban va lap trinh.", {"cpu": "AMD Ryzen 7 7735HS", "ram": "16GB", "storage": "512GB SSD", "gpu": "RTX 4050"}, ["gaming", "programming", "graphics"]),
        ("MacBook Air M2 13", "Apple", 24990000, "Laptop mong nhe cao cap cua Apple, pin lau, hieu nang cao.", {"cpu": "Apple M2", "ram": "8GB", "storage": "256GB SSD"}, ["apple", "macbook", "premium", "lightweight"]),
        ("Acer Aspire 7", "Acer", 16990000, "Laptop hoc tap va lam viec hieu nang tot trong tam gia.", {"cpu": "Intel Core i5-12450H", "ram": "8GB", "storage": "512GB SSD"}, ["student", "office", "budget"]),
        ("Dell XPS 13 Plus", "Dell", 35990000, "Laptop ultrabook doanh nhan cao cap, man hinh OLED dep mat.", {"cpu": "Intel Core i7-1360P", "ram": "16GB", "storage": "1TB SSD"}, ["premium", "ultrabook", "oled", "business"]),
        ("HP Pavilion 14", "HP", 17500000, "Laptop van phong sang trong, thiet ke nhom nguyen khối.", {"cpu": "Intel Core i5-1335U", "ram": "16GB", "storage": "512GB SSD"}, ["office", "hp", "silver"]),
        ("MSI Gaming GF63 Thin", "MSI", 15990000, "Laptop gaming mong nhe gia re cho sinh vien.", {"cpu": "Intel Core i5-11400H", "ram": "8GB", "storage": "512GB SSD", "gpu": "GTX 1650"}, ["gaming", "budget", "msi"]),
        ("Lenovo Legion 5 Pro", "Lenovo", 32990000, "Laptop gaming cao cap, tản nhiat tot, man hinh 165Hz.", {"cpu": "AMD Ryzen 7 7745HX", "ram": "16GB", "storage": "1TB SSD", "gpu": "RTX 4060"}, ["gaming", "legion", "high-end"]),
        ("Asus ROG Strix G16", "Asus", 38990000, "Laptop gaming khung thiet ke noi bat, hieu nang dinh cao.", {"cpu": "Intel Core i7-13650HX", "ram": "16GB", "storage": "1TB SSD", "gpu": "RTX 4070"}, ["rog", "gaming", "esports"]),
        ("MacBook Pro 14 M3", "Apple", 39990000, "Laptop chuyen nghiep cho lap trinh vien va creator.", {"cpu": "Apple M3 Pro", "ram": "18GB", "storage": "512GB SSD"}, ["macbook", "pro", "m3", "developer"]),
        ("LG Gram 16 2024", "LG", 29990000, "Laptop sieu nhe chi 1.1kg, pin dung luong cuc lon.", {"cpu": "Intel Core Ultra 7", "ram": "16GB", "storage": "512GB SSD"}, ["gram", "ultralight", "battery"]),
        ("Acer Predator Helios 16", "Acer", 42990000, "Quai vat gaming man hinh 240Hz OLED.", {"cpu": "Intel Core i9-13900HX", "ram": "32GB", "storage": "1TB SSD", "gpu": "RTX 4080"}, ["predator", "gaming", "extreme"]),
        ("Dell Inspiron 15 3520", "Dell", 13990000, "Laptop van phong gia re ben bỉ.", {"cpu": "Intel Core i3-1215U", "ram": "8GB", "storage": "256GB SSD"}, ["budget", "office", "dell"]),
        ("HP Victus 16", "HP", 21990000, "Laptop gaming thiet ke thanh lich va hieu nang mượt.", {"cpu": "AMD Ryzen 5 7640HS", "ram": "16GB", "storage": "512GB SSD", "gpu": "RTX 3050"}, ["victus", "hp", "gaming"]),
        ("Lenovo ThinkPad X1 Carbon Gen 11", "Lenovo", 45990000, "Bieu tuong laptop doanh nhan, ban phim bam cuc suong.", {"cpu": "Intel Core i7-1365U", "ram": "32GB", "storage": "1TB SSD"}, ["thinkpad", "business", "legendary"]),
        ("Asus ZenBook 14 OLED", "Asus", 24990000, "Laptop mong nhe man hinh OLED 2.8K 120Hz.", {"cpu": "Intel Core Ultra 5", "ram": "16GB", "storage": "512GB SSD"}, ["zenbook", "oled", "fashion"]),
        ("Gigabyte G5 KF", "Gigabyte", 19990000, "Laptop gaming RTX 4060 gia tot nhat thi truong.", {"cpu": "Intel Core i5-12500H", "ram": "16GB", "storage": "512GB SSD", "gpu": "RTX 4060"}, ["gigabyte", "gaming", "valuable"]),
        ("Apple MacBook Air 15 M2", "Apple", 28990000, "MacBook man hinh lon 15 inch mong nhe sang trong.", {"cpu": "Apple M2", "ram": "8GB", "storage": "256GB SSD"}, ["macbook", "air15", "apple"]),
        ("MSI Cyborg 15", "MSI", 18990000, "Laptop gaming vo trong suot phong cach cyberpunk.", {"cpu": "Intel Core i5-12450H", "ram": "8GB", "storage": "512GB SSD", "gpu": "RTX 3050"}, ["msi", "cyberpunk", "gaming"]),
        ("HP Envy x360 14", "HP", 22990000, "Laptop xoay gap 360 do cam ung tien loi.", {"cpu": "Intel Core i5-1335U", "ram": "16GB", "storage": "512GB SSD"}, ["convertible", "touch", "hp"]),
    ],
    "phone": [
        ("iPhone 15 Pro Max", "Apple", 29990000, "Dien thoai cao cap nhat cua Apple vo titan.", {"cpu": "A17 Pro", "screen": "6.7 inch OLED 120Hz"}, ["iphone", "apple", "titanium", "flagship"]),
        ("Samsung Galaxy S24 Ultra", "Samsung", 27990000, "Flagship Android tich hop AI va dung ut S-Pen.", {"cpu": "Snapdragon 8 Gen 3", "screen": "6.8 inch AMOLED"}, ["samsung", "galaxy", "ai", "spen"]),
        ("iPhone 13 128GB", "Apple", 13990000, "Dien thoai iPhone gia tot ban chay nhat.", {"cpu": "A15 Bionic", "screen": "6.1 inch OLED"}, ["iphone", "budget-flagship", "apple"]),
        ("Xiaomi 14 Ultra", "Xiaomi", 24990000, "Dien thoai chuyen chup anh voi qua Leica.", {"cpu": "Snapdragon 8 Gen 3", "screen": "6.73 inch 2K OLED"}, ["xiaomi", "leica", "camera"]),
        ("Samsung Galaxy Z Flip5", "Samsung", 18990000, "Dien thoai man hinh gập thoi trang phong cach.", {"cpu": "Snapdragon 8 Gen 2", "screen": "6.7 inch Foldable"}, ["flip", "samsung", "foldable"]),
        ("iPhone 15 128GB", "Apple", 19990000, "Dien thoai iPhone 15 cong Dynamic Island.", {"cpu": "A16 Bionic", "screen": "6.1 inch OLED"}, ["iphone15", "apple", "dynamic-island"]),
        ("Samsung Galaxy A55 5G", "Samsung", 9990000, "Dien thoai tam trung vo kim loai sang trong.", {"cpu": "Exynos 1480", "screen": "6.6 inch Super AMOLED"}, ["samsung", "midrange", "a55"]),
        ("Xiaomi Redmi Note 13 Pro 5G", "Xiaomi", 6990000, "Dien thoai quoc dan camera 200MP sac 67W.", {"cpu": "Snapdragon 7s Gen 2", "screen": "6.67 inch OLED"}, ["redmi", "budget", "200mp"]),
        ("OPPO Find N3 Flip", "OPPO", 19990000, "Dien thoai gap ngang 3 camera Hasselblad.", {"cpu": "Dimensity 9200", "screen": "6.8 inch Foldable"}, ["oppo", "foldable", "hasselblad"]),
        ("Vivo X100 Pro", "Vivo", 21990000, "Dien thoai nhiep anh dinh cao thong hop voi ZEISS.", {"cpu": "Dimensity 9300", "screen": "6.78 inch LTPO OLED"}, ["vivo", "zeiss", "camera"]),
        ("iPhone 14 Plus", "Apple", 17990000, "iPhone man hinh lon pin cuc trau.", {"cpu": "A15 Bionic", "screen": "6.7 inch OLED"}, ["iphone", "plus", "battery"]),
        ("Samsung Galaxy S23 FE", "Samsung", 12990000, "Phien ban Fan Edition hieu nang cao gia tot.", {"cpu": "Exynos 2200", "screen": "6.4 inch AMOLED"}, ["samsung", "fe", "value"]),
        ("Xiaomi POCO X6 Pro 5G", "Xiaomi", 8490000, "Dien thoai gaming gia re hieu nang vo dich.", {"cpu": "Dimensity 8300 Ultra", "screen": "6.67 inch OLED 120Hz"}, ["poco", "gaming", "budget"]),
        ("OPPO Reno11 Pro 5G", "OPPO", 11990000, "Chuyen gia chan dung thiet ke anh kim sang trong.", {"cpu": "Dimensity 8200", "screen": "6.7 inch OLED"}, ["oppo", "reno", "portrait"]),
        ("Realme GT Neo 5", "Realme", 7990000, "Dien thoai sac sieu nhanh 240W.", {"cpu": "Snapdragon 8+ Gen 1", "screen": "6.74 inch 144Hz"}, ["realme", "fast-charge", "gaming"]),
        ("iPhone 12 64GB", "Apple", 10990000, "iPhone gia re phu hop hoc sinh sinh vien.", {"cpu": "A14 Bionic", "screen": "6.1 inch OLED"}, ["iphone", "budget", "apple"]),
        ("Samsung Galaxy Z Fold5", "Samsung", 32990000, "Dien thoai gap mo bien thanh may tinh bang.", {"cpu": "Snapdragon 8 Gen 2", "screen": "7.6 inch Foldable"}, ["fold", "samsung", "premium"]),
        ("Asus ROG Phone 8 Pro", "Asus", 28990000, "Dien thoai gaming dinh cao co den LED AniMe Vision.", {"cpu": "Snapdragon 8 Gen 3", "screen": "6.78 inch 165Hz"}, ["rog", "gaming-phone", "asus"]),
        ("Google Pixel 8 Pro", "Google", 21990000, "Dien thoai Google Pixel camera AI thuan Google.", {"cpu": "Google Tensor G3", "screen": "6.7 inch OLED"}, ["pixel", "google", "ai-camera"]),
        ("OnePlus 12 5G", "OnePlus", 19990000, "Sieu pham Snapdragon 8 Gen 3 man hinh 2K 4500 nits.", {"cpu": "Snapdragon 8 Gen 3", "screen": "6.82 inch 2K LTPO"}, ["oneplus", "flagship-killer", "smooth"]),
    ],
    "mouse": [
        ("Logitech MX Master 3S", "Logitech", 2499000, "Chuot khong day cong nghe cao cap cho lap trinh va do hoa silent click.", {"sensor": "Darkfield 8000 DPI", "connect": "Bluetooth / Logi Bolt"}, ["mouse", "logitech", "silent", "office"]),
        ("Razer DeathAdder V3 Pro", "Razer", 3290000, "Chuot gaming sieu nhe 63g khong day 4000Hz.", {"sensor": "Focus Pro 30K", "connect": "Razer HyperSpeed"}, ["razer", "gaming", "wireless", "esports"]),
        ("Logitech M331 Silent", "Logitech", 390000, "Chuot khong day gia re chong on va khong tieng dong.", {"sensor": "Optical 1000 DPI", "connect": "USB Receiver"}, ["logitech", "silent", "budget"]),
        ("Logitech G Pro X Superlight 2", "Logitech", 3690000, "Chuot gaming FPS nhe nhat 60g huyen thoai.", {"sensor": "HERO 2 32K DPI", "connect": "LIGHTSPEED Wireless"}, ["logitech", "gpro", "superlight", "fps"]),
        ("Pulsar X2V2 Wireless", "Pulsar", 2190000, "Chuot gaming doi xung sieu nhe 53g.", {"sensor": "PAW3395 26K DPI", "connect": "Wireless 2.4G"}, ["pulsar", "ultralight", "gaming"]),
        ("Logitech Lift Vertical Mouse", "Logitech", 1590000, "Chuot dung ergonomically bao ve co tay chong moi.", {"sensor": "4000 DPI", "connect": "Bluetooth / Logi Bolt"}, ["vertical", "ergonomic", "logitech"]),
        ("SteelSeries Rival 3 Wireless", "SteelSeries", 1190000, "Chuot gaming khong day pin trau 400 gio.", {"sensor": "TrueMove Air", "connect": "Wireless / Bluetooth"}, ["steelseries", "gaming", "wireless"]),
        ("Razer Basilisk V3 Pro", "Razer", 3890000, "Chuot gaming nhieu nut bam cuon vo cuc RGB.", {"sensor": "Focus Pro 30K", "connect": "HyperSpeed Wireless"}, ["razer", "basilisk", "rgb"]),
        ("Logitech G304 LIGHTSPEED", "Logitech", 790000, "Chuot gaming khong day quoc dan gia tot.", {"sensor": "HERO 12K DPI", "connect": "LIGHTSPEED"}, ["logitech", "g304", "budget-gaming"]),
        ("Corsair Katar Pro Wireless", "Corsair", 890000, "Chuot gaming nho gon nhe 96g.", {"sensor": "10000 DPI", "connect": "Slipstream Wireless"}, ["corsair", "wireless", "gaming"]),
        ("Rapoo M650 Silent", "Rapoo", 290000, "Chuot khong day hinh qua trung de thuong silent.", {"sensor": "1300 DPI", "connect": "Bluetooth / 2.4G"}, ["rapoo", "cute", "silent"]),
        ("Glorious Model O Wireless", "Glorious", 1890000, "Chuot gaming to ong RGB sieu nhe 69g.", {"sensor": "BAMF Sensor 19K", "connect": "Wireless 2.4G"}, ["glorious", "honeycomb", "rgb"]),
        ("Zowie EC2-CW Wireless", "Zowie", 3990000, "Chuot gaming FPS chuyen nghiep BenQ Zowie.", {"sensor": "3370 Sensor", "connect": "Enhanced Receiver"}, ["zowie", "csgo", "esports"]),
        ("ASUS ROG Keris Wireless AimPoint", "ASUS", 2190000, "Chuot gaming khong day switch thay the duoc.", {"sensor": "AimPoint 36K DPI", "connect": "Tri-Mode Wireless"}, ["asus", "rog", "gaming"]),
        ("Apple Magic Mouse 2 Black", "Apple", 2290000, "Chuot cam ung Bluetooth sang trong cho Mac.", {"sensor": "Laser", "connect": "Bluetooth / Lightning"}, ["apple", "mac", "magic-mouse"]),
    ],
    "keyboard": [
        ("Keychron K2 V2 Wireless", "Keychron", 1890000, "Ban phim co khong day layout 75% Bluetooth cho Mac va Windows.", {"switch": "Gateron G Pro", "layout": "75%"}, ["keychron", "keyboard", "mac", "wireless"]),
        ("Akko 5075B Plus ISO RGB", "Akko", 1890000, "Ban phim co hotswap numpad giam nhom RGB dep mat.", {"switch": "Akko V3 Cream Yellow", "layout": "75%"}, ["akko", "hotswap", "rgb"]),
        ("Logitech MX Keys S", "Logitech", 2690000, "Ban phim phim bam thap mong nhom sang trong silent.", {"switch": "Low Profile Scissor", "layout": "Fullsize"}, ["logitech", "mxkeys", "office", "silent"]),
        ("Keychron Q1 Max Wireless Custom", "Keychron", 4590000, "Ban phim co nhom nguyen khoi Gasket Mount 2.4G.", {"switch": "Gateron Jupiter", "layout": "75%"}, ["keychron", "custom", "aluminum"]),
        ("Ducky One 3 Mini RGB", "Ducky", 2490000, "Ban phim co 60% chuyen game noi tieng Dai Loan.", {"switch": "Cherry MX Red", "layout": "60%"}, ["ducky", "gaming", "cherry"]),
        ("Akko 3068B Plus World Tour Tokyo", "Akko", 1590000, "Ban phim co mau hong hoa anh dao dep mat.", {"switch": "Akko CS Jelly Pink", "layout": "65%"}, ["akko", "pink", "tokyo"]),
        ("Logitech G PRO X TKL LIGHTSPEED", "Logitech", 4290000, "Ban phim co gaming khong day cao cap TKL.", {"switch": "GX Linear", "layout": "TKL 80%"}, ["logitech", "gpro", "wireless"]),
        ("Razer BlackWidow V4 Pro", "Razer", 5490000, "Ban phim co gaming voi numpad xoay va den RGB 360.", {"switch": "Razer Green Clicky", "layout": "Fullsize"}, ["razer", "green-switch", "rgb"]),
        ("AULA F75 Wireless Hotswap", "AULA", 1190000, "Ban phim co am thanh cuong am gasket mount ngon nhat tam gia.", {"switch": "Reaper Linear", "layout": "75%"}, ["aula", "budget", "creamy-sound"]),
        ("FL-Esports FL750 Wireless", "FL-Esports", 2190000, "Ban phim co san foam am thiet ke dep mat.", {"switch": "FSA profile MX", "layout": "75%"}, ["flesports", "custom", "wireless"]),
        ("Keychron K3 Pro Low Profile", "Keychron", 2390000, "Ban phim co mong nhe hotswap nhieu thiet bi.", {"switch": "Gateron Low Profile", "layout": "75%"}, ["keychron", "low-profile", "slim"]),
        ("Corsair K70 RGB PRO", "Corsair", 3690000, "Ban phim co toc do phan hoi 8000Hz.", {"switch": "Cherry MX Speed Silver", "layout": "Fullsize"}, ["corsair", "k70", "8000hz"]),
        ("Leopold FC900R BT PD", "Leopold", 3490000, "Ban phim co Han Quoc go suong nhat the gioi.", {"switch": "Cherry MX Silent Red", "layout": "Fullsize"}, ["leopold", "korea", "silent"]),
        ("Royal Kludge RK61 Wireless", "Royal Kludge", 790000, "Ban phim co 60% gia re cho sinh vien.", {"switch": "RK Switch", "layout": "60%"}, ["rk61", "budget", "wireless"]),
        ("Varmilo VA87M Sea Melody", "Varmilo", 3290000, "Ban phim co Nghe thuat chu de Dai duong xanh.", {"switch": "Varmilo EC Rose", "layout": "TKL 80%"}, ["varmilo", "art", "blue"]),
    ],
    "headphone": [
        ("Sony WH-1000XM5", "Sony", 7990000, "Tai nghe trum dau chong on chu dong hang dau the gioi.", {"type": "Over-ear ANC", "battery": "30h"}, ["sony", "headphone", "anc", "noise-cancelling"]),
        ("AirPods Pro 2 USB-C", "Apple", 5990000, "Tai nghe in-ear chong on cao cap cua Apple.", {"type": "In-ear TWS ANC", "battery": "6h + 24h"}, ["apple", "airpods", "anc", "tws"]),
        ("Logitech G435 LIGHTSPEED", "Logitech", 1490000, "Tai nghe gaming khong day sieu nhe 165g.", {"type": "Over-ear Wireless", "battery": "18h"}, ["logitech", "gaming", "lightweight", "wireless"]),
        ("Bose QuietComfort Ultra", "Bose", 9990000, "Tai nghe trum dau am thanh vom 3D chong on dinh cao.", {"type": "Over-ear ANC", "battery": "24h"}, ["bose", "anc", "spatial-audio"]),
        ("Sennheiser Momentum 4 Wireless", "Sennheiser", 8490000, "Tai nghe trum dau am thanh Hifi pin 60 gio.", {"type": "Over-ear ANC", "battery": "60h"}, ["sennheiser", "hifi", "long-battery"]),
        ("Sony WF-1000XM5", "Sony", 5490000, "Tai nghe in-ear chong on nho gọn am thanh LDAC Hi-Res.", {"type": "In-ear TWS ANC", "battery": "8h + 16h"}, ["sony", "wf1000xm5", "ldac"]),
        ("AirPods Max USB-C", "Apple", 12990000, "Tai nghe trum dau khong day vo nhom sang trong cua Apple.", {"type": "Over-ear ANC", "battery": "20h"}, ["apple", "airpods-max", "premium"]),
        ("HyperX Cloud II Wireless", "HyperX", 2990000, "Tai nghe gaming huyen thoai cho game thu FPS.", {"type": "Over-ear Gaming", "battery": "30h"}, ["hyperx", "cloud2", "fps-gaming"]),
        ("SteelSeries Arctis Nova Pro Wireless", "SteelSeries", 8990000, "Tai nghe gaming cao cap 2 pin thay hot-swap.", {"type": "Over-ear Gaming ANC", "battery": "Infinite Dual Battery"}, ["steelseries", "nova-pro", "flagship"]),
        ("Marshall Major IV", "Marshall", 3690000, "Tai nghe trum dau co dien hoai co pin 80 gio.", {"type": "On-ear Wireless", "battery": "80h"}, ["marshall", "retro", "rock"]),
        ("Samsung Galaxy Buds2 Pro", "Samsung", 3190000, "Tai nghe in-ear chong on am thanh 24-bit Hi-Fi.", {"type": "In-ear TWS ANC", "battery": "5h + 18h"}, ["samsung", "buds", "hifi"]),
        ("Razer BlackShark V2 Pro 2023", "Razer", 4490000, "Tai nghe gaming mic sieu ro khong day esports.", {"type": "Over-ear Gaming", "battery": "70h"}, ["razer", "blackshark", "esports"]),
        ("Soundpeats Air4 Pro TWS", "Soundpeats", 1290000, "Tai nghe in-ear chong on gia tot ho tro Snapdragon Sound.", {"type": "In-ear TWS ANC", "battery": "6h + 20h"}, ["soundpeats", "budget-anc", "tws"]),
        ("JBL Tune 520BT", "JBL", 1190000, "Tai nghe trum dau gia re am bass manh me pin 57h.", {"type": "On-ear Wireless", "battery": "57h"}, ["jbl", "bass", "budget"]),
        ("Moondrop Chu II In-ear", "Moondrop", 490000, "Tai nghe co day tai nghe audiophile gia re.", {"type": "In-ear Wired", "driver": "Dynamic Driver"}, ["moondrop", "audiophile", "wired"]),
    ],
    "monitor": [
        ("LG UltraGear 27GP850-B", "LG", 7990000, "Man hinh gaming 27 inch Nano IPS 2K 180Hz 1ms.", {"resolution": "2560x1440 2K", "panel": "Nano IPS 180Hz"}, ["lg", "gaming", "2k", "180hz"]),
        ("Dell UltraSharp U2724D", "Dell", 8990000, "Man hinh do hoa 27 inch IPS Black 120Hz mau sac thuc.", {"resolution": "2560x1440 2K", "panel": "IPS Black 120Hz"}, ["dell", "ultrasharp", "color-accurate"]),
        ("ASUS TUF Gaming VG249Q3A", "ASUS", 3490000, "Man hinh gaming 24 inch Fast IPS 180Hz gia re.", {"resolution": "1920x1080 FHD", "panel": "Fast IPS 180Hz"}, ["asus", "tuf", "180hz", "budget"]),
        ("Samsung Odyssey OLED G8", "Samsung", 24990000, "Man hinh cong OLED 34 inch UltraWide 175Hz.", {"resolution": "3440x1440 UWQHD", "panel": "Quantum Dot OLED 175Hz"}, ["samsung", "oled", "curved", "ultrawide"]),
        ("MSI MAG 274QRF QD E2", "MSI", 6890000, "Man hinh Quantum Dot 2K 180Hz do phu mau 98% DCI-P3.", {"resolution": "2560x1440 2K", "panel": "Rapid IPS QD 180Hz"}, ["msi", "quantum-dot", "2k"]),
        ("ViewSonic VX2479-HD-PRO", "ViewSonic", 2690000, "Man hinh SuperClear IPS 165Hz gia tot sinh vien.", {"resolution": "1920x1080 FHD", "panel": "IPS 165Hz"}, ["viewsonic", "budget", "165hz"]),
        ("Gigabyte M27Q Rev 2.0", "Gigabyte", 6290000, "Man hinh gaming 2K IPS tich hop cong tac KVM.", {"resolution": "2560x1440 2K", "panel": "SS IPS 170Hz"}, ["gigabyte", "kvm", "2k"]),
        ("BenQ ZOWIE XL2546K", "BenQ", 11990000, "Man hinh thi dau FPS 240Hz cong nghe DyAc+.", {"resolution": "1920x1080 FHD", "panel": "TN 240Hz DyAc+"}, ["zowie", "240hz", "csgo"]),
        ("AOC Gaming 24G2SP", "AOC", 3190000, "Man hinh gaming quoc dan IPS 165Hz.", {"resolution": "1920x1080 FHD", "panel": "IPS 165Hz"}, ["aoc", "gaming", "budget"]),
        ("ASUS ProArt PA278QV", "ASUS", 7490000, "Man hinh chuyen do hoa Calman Verified 100% sRGB.", {"resolution": "2560x1440 2K", "panel": "IPS 75Hz"}, ["proart", "graphics", "asus"]),
    ]
}

formatted_products = []
current_id = 1

for cat_name, items in categories_data.items():
    for item in items:
        title, brand, price, desc, specs, tags = item
        formatted_products.append({
            "product_id": current_id,
            "title": title,
            "category_id": None,
            "category_name": cat_name,
            "brand": brand,
            "original_price": price,
            "discounted_price": None,
            "discount_percent": None,
            "average_rating": round(4.2 + (current_id % 9) * 0.08, 1),
            "num_ratings": 10 + (current_id * 7) % 150,
            "quantity_sold": 5 + (current_id * 13) % 300,
            "seller_id": 1,
            "description": desc,
            "detailed_review": f"{title} la san pham chat luong cao cua {brand} thuoc danh muc {cat_name}.",
            "powerful_performance": "Hieu nang manh me, hoat dong on dinh.",
            "battery_capacity": str(specs.get("battery", "Standard")),
            "battery_type": "Lithium-ion",
            "color": "Standard",
            "connection_port": str(specs.get("connect", "USB-C")),
            "dimension": "Standard",
            "ram_capacity": str(specs.get("ram", "8GB")),
            "rom_capacity": str(specs.get("storage", "256GB")),
            "screen_size": str(specs.get("screen", "Standard")),
            "weight": str(specs.get("weight", "Standard")),
            "specs": specs,
            "tags": tags,
            "image_url": f"https://example.com/images/{cat_name}-{current_id:03d}.jpg",
            "is_active": True
        })
        current_id += 1

PRODUCTS_FILE.write_text(json.dumps(formatted_products, ensure_ascii=False, indent=2), encoding="utf-8")
print(f"Successfully generated {len(formatted_products)} high quality tech products into {PRODUCTS_FILE}")
